# Generated by Django 4.0.5 on 2022-07-04 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='schedule',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='students_in',
            field=models.ManyToManyField(blank=True, related_name='+', to='mainApp.student'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tutors',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mainApp.tutor'),
        ),
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, to='mainApp.course'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='courses_in',
            field=models.ManyToManyField(blank=True, related_name='+', to='mainApp.course'),
        ),
    ]
