# Generated by Django 4.0.5 on 2022-07-05 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_alter_course_schedule_alter_course_students_in_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor',
            old_name='courses_in',
            new_name='courses',
        ),
    ]
