# Generated by Django 4.0.5 on 2022-06-29 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_rename_user_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='zoom_link',
            field=models.URLField(null=True),
        ),
    ]
